[db]
connection_url = postgresql://exordos_vpn:pass@127.0.0.1:5432/exordos_vpn

[iam]
token_encryption_algorithm = HS256

[token_hs256]
encryption_key = secret

[common]
server_address = platform.exordos.com
ca_cert_file = /etc/openvpn/easy-rsa/pki/ca.crt
ca_key_file = /etc/openvpn/easy-rsa/pki/private/ca.key
tls_auth_file = /etc/openvpn/easy-rsa/ta.key
new_cert_validity_days = 3650
openvpn_client_configs_dir = /etc/openvpn/easy-rsa/configs
server_subnets = 10.10.0.1/22, 10.10.4.1/22
server_port = 1194
server_protocol = tcp
global_salt = change_me_in_production
otp_encryption_key = 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
otp_issuer_name = ExordosVPN
# privatebin_endpoint =

[server_agent]
openvpn_config_dir = /etc/openvpn
openvpn_subnet_cidr = 10.10.0.1/22
firewall_enabled = true
firewall_chain_prefix = exordos_vpn
firewall_global_whitelist = 8.8.8.8/32,1.1.1.1/32

# You can add more configurations here if needed, just add some postfix
[server_agent_udp]
openvpn_config_dir = /etc/openvpn_udp
openvpn_subnet_cidr = 10.10.4.1/22
